spring:
  datasource:
    url: jdbc:mysql://localhost:3306/uia_portal
    username: root
    password: '0704073613'
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql:true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
